### ISSUE TITLE
Photo-gallary sometimes won't start or stops and only display Balena Logo

### ISSUE THREAD

**Issue by geokscott** [balenalabs/balena-dash#106]
Running 3 Pi4's with 
Host OS version balenaOS 2.56.0+rev1
Supervisor version 11.14.0
Current release 60211ae

The only difference in the 3 units is one is on a wired network and the other two are on WiFi network.  The wired seems more stable but exhibits this behavior every once in a while after being rebooted.  The logs last messages after a reboot are:
13.10.20 23:03:17 (+0000)  kiosk  2020/10/13 23:03:17 Starting listening on port 8080
13.10.20 23:03:20 (+0000)  kiosk  Loading gallery
13.10.20 23:03:25 (+0000)  kiosk  2020/10/13 23:03:25 Launch page with desiredURL = 'file:///home/chromium/public_html/index.html'. Slack: false
13.10.20 23:03:25 (+0000)  kiosk  2020/10/13 23:03:25 Redirecting to home page
13.10.20 23:03:25 (+0000)  kiosk  2020/10/13 23:03:25 Running '/home/chromium/launch.sh file:///home/chromium/public_html/index.html'
13.10.20 23:03:25 (+0000)  kiosk  2020/10/13 23:03:25 Responded with home page

But it doesn't get past the Balena Logo.  Just stops there and never displays the Google photo gallery.
I can provide other settings if more info is needed.  I'm at wits end.  I don't know where to look.  The last "run" was everything was working fine for 3 weeks, then the two WiFi units started displaying the Logo.  The logs all looks fine, show the gallery is reloading on schedule every 15 minutes per the Scheduler.....  I rebooted the two WiFi units, tried restarting the app, tried restarting the Kiosk, tried restarting the Gallery.  Finally got one of them working again, but the other is being stubborn.

Any ideas on something to try are welcome!

**Comment by rahul-thakoor** [comment]
Hey there, the photo album feature will be removed in the next major update to this project. we have extracted it into a separate one here https://github.com/balenalabs-incubator/photo-slideshow

Can you try that and see if the issues still persist? 

I'm closing this issue. Also, may I suggest asking questions on our [forums](https://forums.balena.io/) ? It will benefit the community too. Thanks
