### ISSUE TITLE
RP4 display all of the content, but not on the entire Screen for Chromium Update

### ISSUE THREAD

**Issue by rjoel98** [balenalabs/balena-dash#110]
I have been following this project for a while now, and may I start off by saying it is awesome! I recently updated to the latest version as I was hoping it being ported directly from the browser block, some issues would be resolved, main one being the sizing issue I am having on a Vizio 32" screen (Picture of specs and issue attached below.) When I updated, there were quite a few things that were resolved, but unfortunately this was not one... 

I have tried solutions like the one outlined [here](https://github.com/balenalabs/balena-dash/issues/82), and even a large amount of other random configurations as well. The closest I can get is to it filling the entire length, but then it has an even shorter width with using the `WINDOW_SIZE` flag and I set it to 1920, 1080 as recommended. The odd things as that the Balena Logo displays full screen when it boots up, so I know it can display at that size, it's just the browser. Any suggestions?

![TV Specs](https://user-images.githubusercontent.com/24821163/99914069-4a794c00-2cb8-11eb-83fc-cab3e65aaf0f.jpg)

![Normal Configuration](https://user-images.githubusercontent.com/24821163/99914120-6c72ce80-2cb8-11eb-873a-125aebcd584f.jpg)

![1920, 1080 COnfiguration](https://user-images.githubusercontent.com/24821163/99914130-78f72700-2cb8-11eb-8d78-b78afc76140e.jpg)

**Comment by shawaj** [comment]
FYI this is duplicated on the forums https://forums.balena.io/t/rp4-display-all-of-the-content-but-not-on-the-entire-screen-after-chromium-block-update/214846
