### ISSUE TITLE
rpi4 balena dash does not build

### ISSUE THREAD

**Issue by abhatikar** [balenalabs/balena-dash#135]
I am getting this error when I try to push balena dash on rpi 4 connected to a monitor.

![Screenshot_2021-09-01-20-23-48-480_com android chrome](https://user-images.githubusercontent.com/7994511/132108037-c8549165-cb17-4270-a4f9-bb5018701a49.jpg)
![IMG_20210901_202310](https://user-images.githubusercontent.com/7994511/132108040-a468001b-f38b-45b5-a4fa-21dae6c2fe2e.jpg)

> [Logs]    [9/4/2021, 8:28:53 AM] [browser] Enabling kiosk mode
[Logs]    [9/4/2021, 8:28:53 AM] [browser] Enabling cursor
[Logs]    [9/4/2021, 8:28:58 AM] Service exited 'browser sha256:fa7ca3bc2ac4314d5f68595bb8cb219c1b9259cffa39ae6f4617f1024543104c'
[Logs]    [9/4/2021, 8:29:58 AM] Restarting service 'browser sha256:fa7ca3bc2ac4314d5f68595bb8cb219c1b9259cffa39ae6f4617f1024543104c'
[Logs]    [9/4/2021, 8:29:59 AM] [browser] Running balena base image entrypoint...
[Logs]    [9/4/2021, 8:30:00 AM] [browser] setting xserver-xorg-legacy/xwrapper/allowed_users from configuration file
[Logs]    [9/4/2021, 8:30:00 AM] [browser] Using default chromium flags
[Logs]    [9/4/2021, 8:30:00 AM] [browser] Enabling GPU acceleration
[Logs]    [9/4/2021, 8:30:00 AM] [browser] Custom window size set to 800,600
[Logs]    [9/4/2021, 8:30:00 AM] [browser] Using default window position
[Logs]    [9/4/2021, 8:30:00 AM] [browser] Enabling kiosk mode
[Logs]    [9/4/2021, 8:30:00 AM] [browser] Enabling cursor
[Logs]    [9/4/2021, 8:30:04 AM] Service exited 'browser sha256:fa7ca3bc2ac4314d5f68595bb8cb219c1b9259cffa39ae6f4617f1024543104c'
[Logs]    [9/4/2021, 8:31:05 AM] Restarting service 'browser sha256:fa7ca3bc2ac4314d5f68595bb8cb219c1b9259cffa39ae6f4617f1024543104c'
[Logs]    [9/4/2021, 8:31:05 AM] [browser] Running balena base image entrypoint...
[Logs]    [9/4/2021, 8:31:06 AM] [browser] setting xserver-xorg-legacy/xwrapper/allowed_users from configuration file
[Logs]    [9/4/2021, 8:31:06 AM] [browser] Using default chromium flags
[Logs]    [9/4/2021, 8:31:06 AM] [browser] Enabling GPU acceleration
[Logs]    [9/4/2021, 8:31:06 AM] [browser] Custom window size set to 800,600
[Logs]    [9/4/2021, 8:31:06 AM] [browser] Using default window position
[Logs]    [9/4/2021, 8:31:06 AM] [browser] Enabling kiosk mode
[Logs]    [9/4/2021, 8:31:06 AM] [browser] Enabling cursor
[Logs]    [9/4/2021, 8:31:11 AM] Service exited 'browser sha256:fa7ca3bc2ac4314d5f68595bb8cb219c1b9259cffa39ae6f4617f1024543104c'

**Comment by abhatikar** [comment]
The issue is related to the kiosk module which try to build the mozz100/tohora application. Starting 1.16 version, the go command now builds packages in module-aware mode by default, even when no go.mod is present. 
For a workaround, simply add ENV GO111MODULE=off before the RUN go get command in the Dockerfile. However, from 1.17 version of go this flag would also be ignored. Another work around would be, pinning the base image to an older version until this a correctly fixed.  Sorry, I am not a go developer or expert so out of my league :)

> -FROM balenalib/raspberrypi3-golang as builder
> +FROM balenalib/raspberrypi3-golang:1.15-stretch as builder

**Comment by rahul-thakoor** [comment]
thanks for reporting @abhatikar 
fixed by #137
