### ISSUE TITLE
alt_start.sh: line 9: ./tohora: No such file or directory

### ISSUE THREAD

**Issue by J4S0N-H** [balenalabs/balena-dash#138]
I'm not seeing any updates to the UI when I launch BalenaDash. Just the default splash screen remains with the Balena logo. I'm using a Pi4 with HDMI display. I see in the logs that I'm getting the error `alt_start.sh: line 9: ./tohora: No such file or directory`. Looks like this could be the root cause. Looking forward to your response.

**Comment by humblejohn** [comment]
I'm seeing the same issue while using a Raspberry Pi 3 (using 64bit OS) with HDMI display

**Comment by rosswesleyporter** [comment]
This may or may not be related to issue #139

**Comment by phil-d-wilson** [comment]
@J4S0N-H please could you do a new deploy to your fleet? I've just added a fix for this. If you used the DeployWithBalena button, you can reclick it, and select "Use existing application". If you used the CLI and `balena push` then make sure you pull the latest git changes before you push.

**Comment by J4S0N-H** [comment]
Update^. I re-flashed, and set up a new fleet with the latest source. It's all working now! Thanks again for the help!
