### ISSUE TITLE
Suggestion:  Document that the kiosk can be used to display the photo app

### ISSUE THREAD

**Issue by saintaardvark** [balenalabs/balena-dash#81]
Apologies if this is already included somewhere, but I couldn't find anything showing that the kiosk could be made to display the photo app on the monitor.  A user on the forum was asking about this functionality (will link here in a moment).  

On my device, I was able to get this to work by putting `http://[ip address of my device]:8888` into the form at `http://[ip address of my device]:8080`.  My device was in dev mode, though I don't *think* that should make a difference here.

**Edit:** And of course, you can *also* add `http://photos:8888`...which is a lot easier. :stuck_out_tongue_closed_eyes:

**Comment by rahul-thakoor** [comment]
Displaying photo album feature has been extracted into https://github.com/balenalabs-incubator/photo-slideshow

This should work out of the box with the photo slideshow app, so closing this.

Thanks
