### ISSUE TITLE
Black border at the top and left on rpi4

### ISSUE THREAD

**Issue by vbersier** [balenalabs/balena-dash#82]
Hello all,

I'm using this project to display a web-app on the official rpi touchscreen with a raspberry pi 4 and I observe an undesired 3-4mm black border at the top and left sides of the screen.

![IMG_20200616_095353](https://user-images.githubusercontent.com/64898957/84747414-7c72dd80-afb7-11ea-9eb2-f299f411e840.jpg)

I don't know if this is intended or if it happens on the rpi3, but I was wondering if there's a way to remove it?

Thanks!

**Comment by damianpowell** [comment]
Add `--window-position=0,0` to the chromium-browser call in `launch.sh` and `start.sh` in the `kiosk` directory.

**Comment by vbersier** [comment]
Thanks, that fixes it indeed.

**Comment by jkiejr** [comment]
how did you get the dash working on your pi 4

**Comment by vbersier** [comment]
@jkiejr nothing special, I cloned the repo and added the containers to my `docker-compose.yml`. What issues are you experiencing?

**Comment by jkiejr** [comment]
i got it working, it wasnt working for quite a while it was just boot looping, but it seems to have fixed it self

**Comment by rahul-thakoor** [comment]
If you are using balenaCloud, you can create an environment variable `FLAGS` and set it to `$KIOSK --disable-dev-shm-usage --ignore-gpu-blacklist --enable-gpu-rasterization --force-gpu-rasterization --autoplay-policy=no-user-gesture-required --user-data-dir=/usr/src/app/settings --enable-features=WebRTC-H264WithOpenH264FFmpeg --window-position=0,0`
