### ISSUE TITLE
Display resolution

### ISSUE THREAD

**Issue by base1983** [balenalabs/balena-dash#91]
Raspberry pi4 connected to 4k display on HDMI bootsup with 4k res.
When I run `tvservice` -s 
I get `state 0xa [HDMI CUSTOM RGB lim 16:9], 3840x2160 @ 30.00Hz, progressive`

`cat /sys/class/graphics/fb0/virtual_size`
Gives
`1920,1080`

The Kiosk web url now displays on 1/4 of the screen alligned on top left.

Please advise.

**Comment by rahul-thakoor** [comment]
Can you try adding a [Device/Service variable](https://www.balena.io/docs/learn/manage/serv-vars/#environment-and-service-variables) in your balenaCloud dashboard and setting `WINDOW_SIZE` to `3840,2160`?
Let us know if that helps

**Comment by base1983** [comment]
YESSS, this works like a charm. Thnx
